"""Add subscriptions and notifications

Revision ID: c555d55171aa
Revises: 0e2f6004d1a2
Create Date: 2025-12-08 09:52:53.145654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c555d55171aa'
down_revision: Union[str, None] = '0e2f6004d1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificationdelivery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id', 'article_id', name='uq_notification_delivery_subscriber_article')
    )
    op.create_index(op.f('ix_notificationdelivery_article_id'), 'notificationdelivery', ['article_id'], unique=False)
    op.create_index(op.f('ix_notificationdelivery_author_id'), 'notificationdelivery', ['author_id'], unique=False)
    op.create_index(op.f('ix_notificationdelivery_subscriber_id'), 'notificationdelivery', ['subscriber_id'], unique=False)
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id', 'target_user_id', name='uq_subscription_subscriber_target')
    )
    op.create_index(op.f('ix_subscription_subscriber_id'), 'subscription', ['subscriber_id'], unique=False)
    op.create_index(op.f('ix_subscription_target_user_id'), 'subscription', ['target_user_id'], unique=False)
    op.add_column('user', sa.Column('subscription_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscription_key')
    op.drop_index(op.f('ix_subscription_target_user_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_subscriber_id'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_notificationdelivery_subscriber_id'), table_name='notificationdelivery')
    op.drop_index(op.f('ix_notificationdelivery_author_id'), table_name='notificationdelivery')
    op.drop_index(op.f('ix_notificationdelivery_article_id'), table_name='notificationdelivery')
    op.drop_table('notificationdelivery')
    # ### end Alembic commands ###

